### ISSUE TITLE
Alias Request: "Microsoft.Compute/disks.managedby"

### ISSUE THREAD

**Issue by ericyew** [Azure/azure-policy#296] opened 2019-01-11 01:05 UTC
### Scenario
Audit for unattached disks for cost management initiatives

### Alias
- What resource provider and resource type is involved?
Microsoft.Compute/disks.managedby

RP: Microsoft.compute
Resource Type: disks
Property: disks.managedby

- What property on that resource type do you wish to expose?
exist or null

### Example policy definition
`{
  "mode": "indexed",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "Microsoft.Compute/disks.managedby",
          "equals": null
        }
      ]
    },
    "then": {
      "effect": "audit"
    }
  },
  "parameters": {}
}
`

**Comment by artisticcheese** [comment] 2019-01-16 16:49
Confirmed. That property is in fact what you are looking for. 

```
{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Compute/disks"
      },
      {
        "field": "Microsoft.Compute/disks/diskState",
        "equals": "Unattached"
      }
    ]
  },
  "then": {
    "effect": "audit"
  }
}
```

**Comment by ericyew** [comment] 2019-01-21 21:38
Thanks! that works great!

**Comment by mentat9** [comment] 2019-01-23 20:32
Closing this since the scenario is supported a different way.

**Closed by mentat9** 2019-01-23 20:32 UTC
