### ISSUE TITLE
AllowedLocations_Deny: Null location cause false positives

### ISSUE THREAD

**Issue by sean-keane25** [Azure/azure-policy#576] opened 2020-05-28 19:02 UTC
#### Details of the scenario you tried and the problem that is occurring

Resource types of "microsoft.network/networkinterfaces" with a null and empty string location value causes false positives in compliance results. 

#### Verbose logs showing the problem

n/a

#### Suggested solution to the issue

Update the policy rule to exclude resources in which the location value is null or an empty string.

**Comment by pilor** [comment] 2020-05-28 19:44
Location is a required field for all tracked resources (networkInterfaces being one) and is used to route the request to the right backend endpoint.  Can you describe in more detail the scenario that is failing for you?

**Comment by sean-keane25** [comment] 2020-05-28 19:53
The [Microsoft.Network networkInterfaces template reference ](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/networkinterfaces) specifies that the location field is optional. I have seen occurrences of this which then result in false positives in the compliance results for this policy.

**Comment by pilor** [comment] 2020-05-28 19:59
That is an error in their documentation.  Do you have an example PUT request body or template content that demonstrates the issue when this policy is assigned?

**Comment by sean-keane25** [comment] 2020-05-28 22:49
No unfortunately I can not reproduce the issue with an ARM template. I have attempted to do so using all API versions for "Microsoft.Network/networkInterfaces". 

I was able to suppress the majority of the false positives by adding 

```
{
  "field": "location",
  "exists": "true"
}
```
After that change I was still left with a few false positives. I had thought the remaining where empty strings, but I double checked today and the value is 

```
"Location": null,
```

Perhaps a better approach is 

```
{
  "field": "location",
  "notEquals": null
}
```

or

```
{
  "field": "location",
  "notEquals": ""
}
```

Given you indicated that there this is an error in the documentation with regards to location being required and I have found occurrences of null values perhaps at one point the Microsoft.Network/networkInterfaces" API allowed for null values ? At this point I am less concerned about that, and focused on eliminating them in the compliance results for this policy.

**Comment by pilor** [comment] 2020-05-28 22:55
If the false positives are with other resource types make sure your definition has been created using ["mode": "indexed"](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#mode).  That is typically the cause of the problem when users are seeing missing locations causing false positives in location-based policies.

Otherwise, I am going to close this unless a concrete repro is available using a indexed mode policy.

**Closed by pilor** 2020-05-28 22:55 UTC

**Comment by sean-keane25** [comment] 2020-05-28 22:57
The policy is indeed in "mode": "indexed" .
